ALTER TABLE t_user MODIFY COLUMN avatar TEXT DEFAULT NULL COMMENT '头像URL';
ALTER TABLE t_forum_post MODIFY COLUMN avatar TEXT DEFAULT NULL COMMENT '作者头像';
ALTER TABLE t_forum_comment MODIFY COLUMN avatar TEXT DEFAULT NULL COMMENT '作者头像';
ALTER TABLE t_course_comment MODIFY COLUMN user_avatar TEXT DEFAULT NULL COMMENT '用户头像';
